main: com.haralanov.barriers.Barriers
version: 3.0.2
name: Barriers
author: Beezle
website: github.com/AleksandarHaralanov/Barriers
description: Players can create invisible pass-through barrier blocks.

commands:
  barrier:
    description: Toggles placement for barrier blocks.
    usage: /<command>
    aliases: [bar]
  barriers:
    description: See info about the Barriers plugin.
    usage: /<command>

permissions:
  barriers.*:
    description: Allows full access to barrier block features.
    default: op
    children:
      barriers.place: true
      barriers.break: true
  barriers.place:
    description: Allows placement of barrier blocks.
    default: op
  barriers.break:
    description: Allows breaking of barrier blocks.
    default: op